name: local
variables:
  - name: server
    value: http://localhost:3001
  - name: basicUsername
    value: user
  - name: basicPassword
    value: password
  - name: validBasicToken
    value: dXNlcjpwYXNzd29yZA==
  - name: wrongPasswordBasicToken
    value: dXNlcjp3cm9uZw==
  - name: wrongUsernameBasicToken
    value: dW5rbm93bjpwYXNzd29yZA==
